DROP TABLE IF EXISTS eme_habilidad CASCADE;

DROP TABLE IF EXISTS emergencia CASCADE;

DROP TABLE IF EXISTS estado CASCADE;

DROP TABLE IF EXISTS habilidad CASCADE;

DROP TABLE IF EXISTS institucion CASCADE;

DROP TABLE IF EXISTS ranking CASCADE;

DROP TABLE IF EXISTS tarea CASCADE;

DROP TABLE IF EXISTS tarea_habilidad CASCADE;

DROP TABLE IF EXISTS vol_habilidad CASCADE;

DROP TABLE IF EXISTS voluntario CASCADE;

DROP EXTENSION IF EXISTS postgis CASCADE;